services:
  - type: web
    name: docmind-ai
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /_stcore/health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-flash-lite-latest
      - key: GEMINI_EMBEDDING_MODEL
        value: gemini-embedding-001
      - key: PORT
        value: 7860
